name: Daily Data Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Every day at 1:30 AM UTC (adjust to your timezone)
  workflow_dispatch:       # Optional: manual run button in GitHub UI

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # ✅ Valid version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "RETELL_API_KEY=${{ secrets.RETELL_API_KEY }}" >> .env
          echo "SHOPIFY_ACCESS_TOKEN=${{ secrets.SHOPIFY_ACCESS_TOKEN }}" >> .env
          echo "SHOPIFY_STORE=${{ secrets.SHOPIFY_STORE }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Run Retell Fetch Script
        run: python fetch_retell_data.py

      - name: Run Shopify Fetch Script
        run: python fetch_shopify_orders.py

      - name: Run Merge Script
        run: python merge_data.py
