name: Daily Data Update

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hrs
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Retell Fetch Script
        run: python fetch_retell.py

      - name: Run Shopify Fetch Script
        run: python fetch_shopify.py

      - name: Run Merge Script
        run: python merge_new.py
